Traceback (most recent call last):
  File "/mnt/disk1/duyna/FimiCalibIdea/main.py", line 51, in <module>
    model.train()
  File "/mnt/disk1/duyna/FimiCalibIdea/multicalib.py", line 55, in train
    pred = self.model(x, lab)
  File "/home/aiotlab/anaconda3/envs/thanhnt_vaipe/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/disk1/duyna/FimiCalibIdea/models/MulCal_Nmodel.py", line 28, in forward
    _, M, _, _ = input.shape
ValueError: not enough values to unpack (expected 4, got 3)