2022-01-29 14:59:21,775 INFO    MainThread:40491 [wandb_setup.py:_flush():71] setting env: {}
2022-01-29 14:59:21,775 INFO    MainThread:40491 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-29 14:59:21,775 INFO    MainThread:40491 [wandb_init.py:_log_setup():371] Logging user logs to /mnt/disk1/duyna/FimiCalibIdea/wandb/run-20220129_145921-2k10ywr1/logs/debug.log
2022-01-29 14:59:21,776 INFO    MainThread:40491 [wandb_init.py:_log_setup():372] Logging internal logs to /mnt/disk1/duyna/FimiCalibIdea/wandb/run-20220129_145921-2k10ywr1/logs/debug-internal.log
2022-01-29 14:59:21,776 INFO    MainThread:40491 [wandb_init.py:init():404] calling init triggers
2022-01-29 14:59:21,778 INFO    MainThread:40491 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {'metric': 'mse', 'early_stop': 50, 'ssa': False, 'train_type': 'train', 'name': 'MultiCalib_v3', 'data_mean': array([[  14.78165346,   17.64072122,   21.35711413,   59.44086091,
          -2.39303249,   -0.47      ,    1.51866554],
       [  13.23644145,   16.27106598,   21.62654448,   58.20988112,
          -2.5734684 ,   -0.49      ,   -0.99728948],
       [  18.5979364 ,   20.28432732,   20.83205865,   66.80813652,
          -2.59591143,   -0.54      ,    0.21797008],
       [  15.40962057,   17.94272439,   19.85355062,   61.12765207,
        -168.60635427,   -0.48      ,    0.18787398],
       [  14.6675847 ,   17.50958193,   20.75632059,   59.30897167,
          -1.96892808,   -0.43      ,    0.2655637 ]]), 'data_std': array([[3.58519450e+00, 3.57261641e+00, 8.83224486e-01, 1.35361314e+00,
        2.70505421e-01, 1.65980270e-14, 8.04884486e-02],
       [3.21244568e+00, 3.21992214e+00, 8.91711716e-01, 9.16114787e-01,
        3.28210917e-01, 7.05681906e-15, 8.94921263e-02],
       [5.08454728e+00, 5.04351136e+00, 1.05356075e+00, 1.96271228e+00,
        2.33812707e-01, 6.66133815e-15, 2.89966197e-02],
       [4.23094176e+00, 4.19768511e+00, 1.05904152e+00, 1.64564757e+00,
        9.80233763e+00, 9.76996262e-15, 2.32984120e-02],
       [3.79094376e+00, 3.74450144e+00, 1.08283067e+00, 1.90160911e+00,
        2.33978282e-01, 3.83026943e-15, 2.90224593e-02]])}
2022-01-29 14:59:21,778 INFO    MainThread:40491 [wandb_init.py:init():460] starting backend
2022-01-29 14:59:21,778 INFO    MainThread:40491 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-01-29 14:59:21,854 INFO    MainThread:40491 [backend.py:ensure_launched():216] starting backend process...
2022-01-29 14:59:21,945 INFO    MainThread:40491 [backend.py:ensure_launched():221] started backend process with pid: 48543
2022-01-29 14:59:21,946 INFO    MainThread:40491 [wandb_init.py:init():469] backend started and connected
2022-01-29 14:59:21,958 INFO    MainThread:40491 [wandb_init.py:init():533] updated telemetry
2022-01-29 14:59:22,139 INFO    MainThread:40491 [wandb_init.py:init():563] communicating current version
2022-01-29 14:59:23,313 INFO    MainThread:40491 [wandb_init.py:init():568] got version response 
2022-01-29 14:59:23,313 INFO    MainThread:40491 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-29 14:59:24,050 INFO    MainThread:40491 [wandb_init.py:init():606] starting run threads in backend
2022-01-29 14:59:29,058 INFO    MainThread:40491 [wandb_run.py:_console_start():1810] atexit reg
2022-01-29 14:59:29,058 INFO    MainThread:40491 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.REDIRECT
2022-01-29 14:59:29,059 INFO    MainThread:40491 [wandb_run.py:_redirect():1689] Redirecting console.
2022-01-29 14:59:29,062 INFO    MainThread:40491 [wandb_run.py:_redirect():1745] Redirects installed.
2022-01-29 14:59:29,062 INFO    MainThread:40491 [wandb_init.py:init():633] run started, returning control to user process
2022-01-29 14:59:29,083 INFO    MainThread:40491 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 1
2022-01-29 14:59:29,086 INFO    MainThread:40491 [wandb_run.py:_restore():1752] restore
2022-01-29 14:59:32,242 INFO    MainThread:40491 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
}
pusher_stats {
}

2022-01-29 14:59:32,426 INFO    MainThread:40491 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  total_bytes: 859
}

2022-01-29 14:59:32,842 INFO    MainThread:40491 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 859
  total_bytes: 859
}

2022-01-29 14:59:33,069 INFO    MainThread:40491 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 859
  total_bytes: 12061
}

2022-01-29 14:59:33,172 INFO    MainThread:40491 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 859
  total_bytes: 13850
}

2022-01-29 14:59:33,274 INFO    MainThread:40491 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 859
  total_bytes: 13850
}

2022-01-29 14:59:33,377 INFO    MainThread:40491 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 859
  total_bytes: 13850
}

2022-01-29 14:59:33,480 INFO    MainThread:40491 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 859
  total_bytes: 13850
}

2022-01-29 14:59:33,584 INFO    MainThread:40491 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 3179
  total_bytes: 13850
}

2022-01-29 14:59:33,687 INFO    MainThread:40491 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 13824
  total_bytes: 13850
}

2022-01-29 14:59:33,790 INFO    MainThread:40491 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 13824
  total_bytes: 13850
}

2022-01-29 14:59:33,893 INFO    MainThread:40491 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 13824
  total_bytes: 13850
}

2022-01-29 14:59:33,998 INFO    MainThread:40491 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 13824
  total_bytes: 13850
}

2022-01-29 14:59:34,101 INFO    MainThread:40491 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 13850
  total_bytes: 13850
}

2022-01-29 14:59:34,203 INFO    MainThread:40491 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 13850
  total_bytes: 13850
}

2022-01-29 14:59:34,305 INFO    MainThread:40491 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 13850
  total_bytes: 13850
}

2022-01-29 14:59:34,408 INFO    MainThread:40491 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 13850
  total_bytes: 13850
}

2022-01-29 14:59:34,510 INFO    MainThread:40491 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 13850
  total_bytes: 13850
}

2022-01-29 14:59:34,612 INFO    MainThread:40491 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 13850
  total_bytes: 13850
}

2022-01-29 14:59:35,190 INFO    MainThread:40491 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 13850
  total_bytes: 13850
}

2022-01-29 14:59:35,940 INFO    MainThread:40491 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 13850
  total_bytes: 13850
}
local_info {
}

2022-01-29 14:59:37,127 INFO    MainThread:40491 [wandb_run.py:_append_files():2180] logging synced files
